"""Publisher paths checked 2026-09-07; failures are kept visible, not silently ignored."""
NEWS_SOURCES = [
    dict(id="bbc", name="BBC", type="rss", language="en", region="세계", category="세계",
         url="https://feeds.bbci.co.uk/news/world/middle_east/rss.xml", enabled=True),
    dict(id="reuters", name="Reuters", type="rss", language="en", region="세계", category="세계",
         url="https://news.google.com/rss/search?q=site:reuters.com+(Iraq+OR+Iran+OR+%22Middle+East%22)&hl=en-US&gl=US&ceid=US:en", enabled=True, metadata_only=True, publisher_host="reuters.com", note="Google News 경유 제목·게시일·링크 수집 — 공식 본문 연결 미확보"),
    dict(id="aljazeera", name="Al Jazeera", type="rss", language="en", region="세계", category="세계",
         url="https://www.aljazeera.com/xml/rss/all.xml", enabled=True),
    dict(id="ina", name="INA", type="listing", language="ar", region="이라크", category="미분류",
         url="https://ina.iq/",
         article_pattern=r"/ar/(?:political|local|economie|security|international)/[0-9]+[^/]*\.html$",
         recent_id_window=500,
         relevance_sections=("political", "security", "economie"),
         relevance_terms=("العراق", "العراقي", "الحكومة", "البرلمان", "الاستثمار", "السكن",
                          "الإعمار", "الاقتصاد", "النفط", "الطاقة", "الكهرباء", "الجمارك",
                          "هرمز", "إيران", "أمريكا", "داعش", "مشروع"),
         enabled=True, body_fetch_review=True,
         note="공식 홈페이지 최신 기사 목록·본문 자동 수집 — 접근 실패 기사만 검토 대기"),
    dict(id="shafaq", name="Shafaq", type="rss", language="ar", region="이라크", category="미분류",
         url="https://shafaq.com/ar?rss=1", enabled=True),
    dict(id="964media", name="964media", type="discover_rss", language="ar", region="이라크", category="미분류",
         url="https://964media.com/", enabled=True),
    dict(id="baghdadtoday", name="Baghdad Today", type="rss", language="ar", region="이라크", category="미분류",
         url="https://baghdadtoday.news/rss.xml", enabled=True),
    dict(id="alsumaria", name="Alsumaria", type="rss", language="ar", region="이라크", category="미분류",
         url="https://www.alsumaria.tv/Rss/iraq-latest-news/ar", enabled=True),
    dict(id="almada", name="Almada", type="listing", language="ar", region="이라크", category="미분류",
         url="https://almadapaper.net/", article_pattern=r"/[0-9]{4,}/?$", enabled=True,
         note="공개 목록의 제목·링크만 수집, 본문 AI 사용은 별도 확인"),
    dict(id="alrabiaa", name="Alrabiaa", type="rss", language="ar", region="이라크", category="미분류",
         url="https://news.google.com/rss/search?q=site%3Aalrabiaa.tv+(%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82+OR+%D8%A8%D8%BA%D8%AF%D8%A7%D8%AF+OR+%D8%A5%D9%8A%D8%B1%D8%A7%D9%86+OR+%D9%87%D8%B1%D9%85%D8%B2+OR+%D8%A7%D9%84%D8%AD%D9%83%D9%88%D9%85%D8%A9+OR+%D8%A7%D9%84%D9%86%D9%81%D8%B7)&hl=ar&gl=IQ&ceid=IQ%3Aar",
         enabled=True, metadata_only=True, publisher_host="alrabiaa.tv",
         relevance_sections=("iraq",),
         relevance_terms=("العراق", "بغداد", "الحكومة", "البرلمان", "الاستثمار", "النفط", "أمن", "إيران", "هرمز", "إسرائيل", "لبنان", "اليمن", "غزة", "الحشد", "داعش", "كهرباء", "سكن"),
         note="Google News 경유 제목·게시일·링크 수집 — 공식 사이트 응답 지연으로 본문은 별도 확인"),
    dict(id="kurdistan24", name="Kurdistan24", type="listing", language="en", region="이라크", category="미분류",
         url="https://www.kurdistan24.net/en", article_pattern=r"/en/story/[0-9]+/", enabled=True,
         note="공개 목록의 제목·링크 수집, 게시일 없으면 수집일로 구분"),
    dict(id="ft", name="FT", type="rss", language="en", region="세계", category="세계",
         url="https://www.ft.com/world?format=rss", enabled=True, metadata_only=True, note="공식 RSS 제목·요약 수집 — 유료 본문 미수집"),
    dict(id="nyt", name="NYT", type="rss", language="en", region="세계", category="세계",
         url="https://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml", enabled=True, metadata_only=True, note="공식 중동 RSS 제목·요약 수집 — 유료 본문 미수집"),
]
