create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  source text, category text, title text, ai_title text, summary text,
  original text, language text, published_at text, collected_at text, url text,
  report_status text not null default 'pending', report_reason text,
  edited_title text, edited_summary text, edit_revision integer not null default 0,
  canonical_url text, title_hash text, body_hash text, report_date text,
  date_basis text, week_start text, duplicate_of bigint, region text, excerpt text
);

create index if not exists articles_period on public.articles(week_start, report_status);
create index if not exists articles_title_date on public.articles(title_hash, report_date);
create unique index if not exists articles_canonical_url on public.articles(canonical_url) where canonical_url is not null;

create table if not exists public.source_checks (
  source_id text primary key, name text, status text, note text,
  checked_at text, counts text not null default '{}'
);

create table if not exists public.analysis_attempts (
  id bigint generated by default as identity primary key,
  article_id bigint not null, day text not null,
  started_at text not null default current_timestamp::text, status text not null,
  unique(article_id, day)
);

create table if not exists public.job_runs (
  id bigint generated by default as identity primary key,
  job text not null, started_at text not null, finished_at text,
  status text not null, detail text
);
create index if not exists job_runs_job_id on public.job_runs(job, id desc);

create table if not exists public.ai_spend (
  id bigint generated by default as identity primary key,
  day text not null, reserved bigint not null, charged bigint,
  status text not null default 'reserved'
);

create table if not exists public.ai_budget_state (
  day text primary key, daily_limit bigint, monthly_limit bigint,
  blocked integer not null default 0
);

alter table public.articles enable row level security;
alter table public.source_checks enable row level security;
alter table public.analysis_attempts enable row level security;
alter table public.job_runs enable row level security;
alter table public.ai_spend enable row level security;
alter table public.ai_budget_state enable row level security;

revoke all on public.articles, public.source_checks, public.analysis_attempts,
  public.job_runs, public.ai_spend, public.ai_budget_state from anon, authenticated;
